app = 'bdp-registry-migrations-dev'
primary_region = 'ams'

[build]
dockerfile = 'src/BDP.Registry.Persistence/Dockerfile.migrations'

[deploy]
strategy = 'immediate'
release_command = './efbundle'

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1

[[services]]
protocol = ''
internal_port = 0
